name: Deploy App to AWS

on:
  push:
    branches:
    - main

jobs:
  # Run unit and integration tests
  tests:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
      statuses: write
    steps:
    - name: Get git output names
      id: git
      shell: bash
      run: |
        if [[ "${{ github.ref }}" != "refs/tags/"* ]]; then
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "::set-output name=current_branch::$HEAD_REF"
          else
            echo "::set-output name=current_branch::$REF_BRANCH"
          fi
        else
          REF=$(printf "%q" "${{ github.ref }}")
          REF_BRANCH=${REF/refs\/tags\/${{ inputs.strip_tag_prefix }}/}
          echo "::set-output name=current_branch::$(eval printf "%s" "$REF_BRANCH")"
        fi
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.x


    - name: cloning the repo
      run: git clone https://github.com/facebookincubator/nvdtools.git

    - name: installing nvdtools
      run: |
        #!bin/bash
        cd ./nvdtools/cmd
        go install ./...
        cd nvdsync
        go build
        ls -la


