name: Deploy App to AWS

on:
  push:
    branches:
    - main

jobs:
  # Run unit and integration tests
  tests:
    strategy:
      matrix:
        go-version: [1.13.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      deployments: write
      contents: read
      statuses: write
    steps:
    - name: Get git output names
      id: git
      shell: bash
      run: |
        if [[ "${{ github.ref }}" != "refs/tags/"* ]]; then
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "::set-output name=current_branch::$HEAD_REF"
          else
            echo "::set-output name=current_branch::$REF_BRANCH"
          fi
        else
          REF=$(printf "%q" "${{ github.ref }}")
          REF_BRANCH=${REF/refs\/tags\/${{ inputs.strip_tag_prefix }}/}
          echo "::set-output name=current_branch::$(eval printf "%s" "$REF_BRANCH")"
        fi
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}


    - name: installing nvdtools
      run: |
        cd ./cmd
        go install ./...


    - name: changing ownership
      run: |
        #!/bin/bash
        #cd ./cmd/nvdsync
        echo "Workspace directory: $GITHUB_WORKSPACE"
        sudo chown -R root:root $GITHUB_WORKSPACE
        sudo chmod +x $GITHUB_WORKSPACE/*
        ls -la
        
